apiVersion: 2021-10-01
location: ${AZ_LOCATION}
name: ${MYSQL_ACI_NAME}
properties:
  imageRegistryCredentials:
    - server: ${ACR_LOGIN_SERVER}
      username: ${ACR_USERNAME}
      password: ${ACR_PASSWORD}
  containers:
    - name: mysql
      properties:
        image: ${MYSQL_IMAGE}
        ports:
          - port: 3306
        environmentVariables:
          - name: MYSQL_ROOT_PASSWORD
            secureValue: "${MYSQL_ROOT_PASSWORD}"
          - name: MYSQL_DATABASE
            value: "${MYSQL_DB}"
          - name: MYSQL_USER
            value: "${MYSQL_USER}"
          - name: MYSQL_PASSWORD
            secureValue: "${MYSQL_PASSWORD}"
        resources:
          requests:
            cpu: 1.0
            memoryInGb: 2.0
        volumeMounts:
          - name: mysql-share
            mountPath: /mnt/share
  osType: Linux
  ipAddress:
    type: Public
    ports:
      - protocol: TCP
        port: 3306
    dnsNameLabel: ${MYSQL_DNS_LABEL}
  volumes:
    - name: mysql-share
      azureFile:
        shareName: ${FILESHARE_NAME}
        storageAccountName: ${STG_NAME}
        storageAccountKey: ${STG_KEY}
type: Microsoft.ContainerInstance/containerGroups
