apiVersion: 2021-10-01
location: brazilsouth
name: motohub-rm558883
properties:
  containers:
    - name: mysql
      properties:
        image: mysql:8.4
        ports:
          - port: 3306
        environmentVariables:
          - name: MYSQL_ROOT_PASSWORD
            secureValue: "RootPass_ChangeMe!"
          - name: MYSQL_DATABASE
            value: "motohub"
          - name: MYSQL_USER
            value: "motohub"
          - name: MYSQL_PASSWORD
            secureValue: "AppPass_ChangeMe!"
        resources:
          requests:
            cpu: 1.0
            memoryInGb: 2.0
        volumeMounts:
          - name: mysql-share
            mountPath: /mnt/share

    - name: motohub-api
      properties:
        image: motohubrm558883acr.azurecr.io/motohub-api:v4
        ports:
          - port: 8080
        environmentVariables:
          - name: APP_PORT
            value: "8080"
          - name: DB_HOST
            value: "127.0.0.1"
          - name: DB_PORT
            value: "3306"
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:mysql://127.0.0.1:3306/motohub?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
          - name: SPRING_DATASOURCE_USERNAME
            value: "motohub"
          - name: SPRING_DATASOURCE_PASSWORD
            secureValue: "AppPass_ChangeMe!"
          - name: SPRING_AUTOCONFIGURE_EXCLUDE
            value: "org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration"
          - name: SPRING_FLYWAY_ENABLED
            value: "false"
          - name: SPRING_JPA_HIBERNATE_DDL_AUTO
            value: "none"
        resources:
          requests:
            cpu: 1.0
            memoryInGb: 2.0

  osType: Linux
  ipAddress:
    type: Public
    ports:
      - protocol: TCP
        port: 8080
    dnsNameLabel: motohub-rm558883

  imageRegistryCredentials:
    - server: motohubrm558883acr.azurecr.io
      username: motohubrm558883acr
      password: MZAuKCao7UrChwpI6RBCekCah3+/pMpZtnkRWeKZeR+ACRB1Nqxm

  volumes:
    - name: mysql-share
      azureFile:
        shareName: fs-mysql
        storageAccountName: stmotohubrm558883
        storageAccountKey: ib5vBT0gDdKLP+3KOKJFZ+NsAELKMe5ZGaVSxLUARqQyIRUc2RQT41qVxu0rQKP8KWOzSSNragy9+AStKL3ytw==

type: Microsoft.ContainerInstance/containerGroups
