CREATE TABLE usuario (
  id BIGINT IDENTITY(1,1) PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  password VARCHAR(100) NOT NULL,
  [role] VARCHAR(20) NOT NULL
);

CREATE TABLE cliente (
  id BIGINT IDENTITY(1,1) PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(100)
);

CREATE TABLE moto (
  id BIGINT IDENTITY(1,1) PRIMARY KEY,
  modelo VARCHAR(50) NOT NULL,
  marca VARCHAR(50) NOT NULL,
  tipo_uso VARCHAR(20) NOT NULL
);
